# Generated by Django 2.0.4 on 2018-04-21 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('preview', models.ImageField(blank=True, default='default.png', null=True, upload_to='', verbose_name='preview')),
                ('mode', models.CharField(choices=[('0', 'Empty'), ('1', 'Once'), ('2', 'Loop')], max_length=1, verbose_name='mode')),
                ('static', models.BooleanField(default=False, verbose_name='static')),
            ],
        ),
    ]
