# Generated by Django 2.0.4 on 2018-04-21 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stream',
            options={'verbose_name': 'Stream', 'verbose_name_plural': 'Streams'},
        ),
        migrations.RemoveField(
            model_name='stream',
            name='static',
        ),
        migrations.AddField(
            model_name='stream',
            name='online',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='online'),
        ),
        migrations.AlterField(
            model_name='stream',
            name='start',
            field=models.IntegerField(blank=True, null=True, verbose_name='start'),
        ),
    ]
