# Generated by Django 2.0.4 on 2018-04-23 09:34

import backend.media.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('0', 'Image'), ('1', 'Audio'), ('2', 'Video')], max_length=1, verbose_name='type')),
                ('file', models.FileField(blank=True, null=True, upload_to=backend.media.models.Content.upload_to, verbose_name='file')),
                ('length', models.IntegerField(blank=True, null=True, verbose_name='length')),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('align', models.CharField(choices=[('0', 'Audio'), ('1', 'Video')], max_length=1, verbose_name='align')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('audio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medias_audio', to='media.Content', verbose_name='audio')),
                ('video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medias_video', to='media.Content', verbose_name='video')),
            ],
        ),
    ]
